# MinIO S3 credentials secret for Tempo (using shared MinIO instance)
apiVersion: v1
kind: Secret
metadata:
  name: minio-tempo-credentials
  namespace: {{ include "tempo-stack.namespace" . }}
  labels:
    {{- include "tempo-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: tempo-storage
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  # S3 credentials for Tempo (points to shared MinIO)
  access_key_id: {{ .Values.minio.s3.accessKeyId }}
  access_key_secret: {{ .Values.minio.s3.accessKeySecret }}
  bucket: {{ .Values.minio.s3.bucket }}
  endpoint: {{ .Values.minio.s3.endpoint }}