---
# Operator: loki-operator
# Full Name: loki-operator.openshift-loki-operator
# CRD Patterns: loki.grafana.com
# Note: Uninstalling this operator will delete all CRDs matching the above patterns
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: ${NAMESPACE}-
  namespace: ${NAMESPACE}
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: loki-operator
  namespace: ${NAMESPACE}
spec:
  channel: stable-6.0
  name: loki-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
