{{- if .Values.rbac.create }}
# ClusterRole for Loki tenant access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "loki-stack.clusterResourceName" . }}-tenant-logs
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
rules:
- apiGroups:
  - 'loki.grafana.com'
  resources:
  - application
  - infrastructure
  - audit
  resourceNames:
  - logs
  verbs:
  - 'get'
  - 'create'
---
# ClusterRoleBinding for log collection service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "loki-stack.clusterResourceName" . }}-tenant-logs
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "loki-stack.clusterResourceName" . }}-tenant-logs
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.collector.serviceAccount.name }}
  namespace: {{ .Values.rbac.collector.serviceAccount.namespace }}
{{- if .Values.rbac.serviceAccounts.logForwarder.create }}
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccounts.logForwarder.name }}
  namespace: {{ include "loki-stack.namespace" . }}
{{- end }}
---
{{- if .Values.rbac.serviceAccounts.logForwarder.create }}
# Service account for log forwarding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccounts.logForwarder.name }}
  namespace: {{ include "loki-stack.namespace" . }}
  labels:
    {{- include "loki-stack.labels" . | nindent 4 }}
{{- end }}
{{- end }}
